import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {FRUIT_MIX,cutPose,CUT_CONTACT,CUT_RELEASE,CUT_END,FruitCadence,NEXT_FRUIT_DELAY} from '../src/sentence-motion.ts';
assert.deepEqual([...FRUIT_MIX],['apple','kiwi','pear','orange','mango']);
assert.equal(cutPose(CUT_CONTACT-.001).split,false);
assert.equal(cutPose(CUT_CONTACT).split,true);
assert.ok(cutPose(CUT_CONTACT).blade<.03,'blade reaches board before separation');
assert.equal(cutPose(CUT_CONTACT).spread,0);
assert.equal(cutPose(CUT_RELEASE).transfer,0,'pieces stay on board until separation completes');
assert.equal(cutPose(CUT_END).transfer,1);
assert.equal(cutPose(CUT_END).settled,true);
const cadence=new FruitCadence();
assert.equal(cadence.ready(0),true);
cadence.finish(CUT_END);
for(const now of [CUT_END,CUT_END+NEXT_FRUIT_DELAY/2,CUT_END+NEXT_FRUIT_DELAY-.001])assert.equal(cadence.ready(now),false,'no replacement fruit during rest');
assert.equal(cadence.ready(CUT_END+NEXT_FRUIT_DELAY),true);
cadence.finish(3);assert.equal(cadence.ready(3.1),false);
assert.equal(cadence.ready(3.1),false,'paused scene time does not consume the delay');
cadence.reset();assert.equal(cadence.ready(0),true,'replay can prepare its first fruit immediately');
const glb=await readFile(new URL('../public/assets/typeslasher-kitchen.glb',import.meta.url));
assert.equal(glb.toString('utf8',0,4),'glTF');
const doc=JSON.parse(glb.toString('utf8',20,20+glb.readUInt32LE(12)));
for(const name of ['kitchen_environment','chef_knife','service_bowl'])assert.ok(doc.nodes.some(n=>n.name===name),name);
assert.ok(!doc.nodes.some(n=>/pendant|food_|review camera/i.test(n.name??'')),'no lamps or static review fruit in the runtime kitchen');
assert.ok(doc.images.length>=4,'wood, end grain, stone and cloth textures exported');
assert.ok(doc.images.every(image=>image.bufferView!==undefined),'textures are embedded for portable play');
const clearance=JSON.parse(await readFile(new URL('../art-review/kitchen-v2-clearance.json',import.meta.url),'utf8'));
assert.equal(clearance.pendants.length,0);
assert.equal(clearance.shelf_props.length,10);
for(const prop of clearance.shelf_props){assert.ok(prop.front>=2.15&&prop.back<=3.47);assert.ok(prop.wall_clearance>.18);}
console.log('Passed: fruit mix, blade/split/transfer order, Blender export, embedded textures and shelf clearances.');
